# Generated by Django 4.2.4 on 2023-08-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(default='New book', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BookUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookId', models.IntegerField(default=1)),
                ('UserId', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='New Counterparty', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISIN', models.IntegerField(default=0)),
                ('CUSIP', models.IntegerField(default=0)),
                ('Issuer', models.CharField(default='NA', max_length=200)),
                ('MaturityDate', models.DateTimeField()),
                ('Coupon', models.IntegerField(default=0)),
                ('Type', models.CharField(choices=[('1', 'Type 1'), ('2', 'Type 2'), ('3', 'Type 3'), ('4', 'Type 4')], default='1', max_length=10)),
                ('FaceValue', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('s', 'Success'), ('f', 'Failed'), ('p', 'Pending'), ('na', 'Not Available')], default='na', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookId', models.IntegerField(default=1)),
                ('CounterpartyId', models.IntegerField(default=1)),
                ('SecurityId', models.IntegerField(default=1)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('s', 'Success'), ('f', 'Failed'), ('p', 'Pending'), ('na', 'Not Available')], default='na', max_length=10)),
                ('Price', models.IntegerField(default=0)),
                ('Buy_Sell', models.CharField(choices=[('b', 'Buy'), ('s', 'Sell')], default='b', max_length=10)),
                ('TradeDate', models.DateTimeField(auto_now_add=True)),
                ('SettlementDate', models.DateTimeField()),
            ],
        ),
    ]
